// ============================================================
// 萌系机甲机器人 Chibi Mecha Robot — 参数化3D模型 v2
// Generated by ModelForge (Cascade Agent)
// Reference: chibi mech robot with helmet head, armor plates,
//            shoulder pads, mechanical arms, chunky mech legs
// ============================================================

/* [整体 / Overall] */
scale_factor = 1.0;     // [0.5:0.1:3.0] 整体缩放 Overall scale

/* [头部 / Head] */
head_w = 44;             // [32:1:60] 头盔宽度 Helmet width (mm)
head_h = 34;             // [24:1:48] 头盔高度 Helmet height (mm)
head_d = 38;             // [26:1:50] 头盔深度 Helmet depth (mm)
visor_w = 28;            // [18:1:40] 面罩宽度 Visor width (mm)
visor_h = 14;            // [8:1:22] 面罩高度 Visor height (mm)
ear_r = 8;               // [5:1:12] 耳件半径 Ear pod radius (mm)
ear_d = 8;               // [3:1:10] 耳件厚度 Ear pod depth (mm)
eye_r = 4;               // [2:0.5:6] 眼睛半径 Eye radius (mm)
eye_sp = 13;             // [8:1:20] 眼距 Eye spacing (mm)
crest_h = 4;             // [2:1:8] 头顶嵴高度 Crest height (mm)

/* [天线 / Antenna] */
ant_h = 8;               // [4:1:16] 天线高度 Antenna height (mm)
ant_r = 2;               // [1:0.5:4] 天线顶部半径 Antenna top radius (mm)

/* [躯干 / Torso] */
tor_w = 32;              // [22:1:44] 躯干宽度 Torso width (mm)
tor_h = 20;              // [14:1:30] 躯干高度 Torso height (mm)
tor_d = 24;              // [16:1:36] 躯干深度 Torso depth (mm)
chest_w = 20;            // [12:1:30] 胸甲宽度 Chest plate width (mm)
chest_h = 10;            // [6:1:18] 胸甲高度 Chest plate height (mm)

/* [肩甲 / Shoulder Pads] */
sh_w = 14;               // [8:1:20] 肩甲宽度 Shoulder pad width (mm)
sh_h = 12;               // [8:1:18] 肩甲高度 Shoulder pad height (mm)
sh_d = 14;               // [8:1:20] 肩甲深度 Shoulder pad depth (mm)

/* [手臂 / Arms] */
ua_len = 10;             // [6:1:18] 上臂长度 Upper arm length (mm)
ua_w = 8;                // [5:1:12] 上臂宽度 Upper arm width (mm)
fa_len = 10;             // [6:1:18] 前臂长度 Forearm length (mm)
fa_w = 9;                // [5:1:14] 前臂宽度 Forearm width (mm)
hand_w = 8;              // [5:1:12] 手掌宽度 Hand width (mm)
arm_angle = 50;          // [0:5:90] 手臂外展角 Arm spread angle (deg)

/* [腿部 / Legs] */
thigh_len = 12;          // [8:1:20] 大腿长度 Thigh length (mm)
thigh_w = 11;            // [6:1:14] 大腿宽度 Thigh width (mm)
calf_len = 12;           // [8:1:20] 小腿长度 Calf length (mm)
calf_w = 12;             // [7:1:16] 小腿宽度 Calf width (mm)
foot_w = 16;             // [10:1:24] 脚掌宽度 Foot width (mm)
foot_d = 14;             // [8:1:20] 脚掌深度 Foot depth (mm)
foot_h = 6;              // [3:1:10] 脚掌高度 Foot height (mm)
leg_sp = 18;             // [12:1:28] 两腿间距 Leg spacing (mm)
knee_w = 12;             // [8:1:16] 膝甲宽度 Knee armor width (mm)

/* [渲染 / Render] */
quality = 48;            // [16:8:128] 渲染精度 Render quality

// ============================================================
// 头盔 Helmet Module — 穹顶形，面罩凹入，侧耳件
// ============================================================
module helmet() {
    hw = head_w/2; hh = head_h/2; hd = head_d/2;

    difference() {
        union() {
            // 头盔主体：穹顶 = 上半球 + 下方块 hull
            hull() {
                // 顶部穹顶（扁球体，只取上半）
                translate([0, 0, 2])
                    resize([head_w, head_d, head_h*1.1])
                        sphere(r=10, $fn=quality);
                // 底部下巴区域（方块，比穹顶窄）
                translate([0, 0, -hh+2])
                    cube([head_w*0.85, head_d*0.8, 4], center=true);
            }

            // 头顶嵴（中央凸起条）
            translate([0, 0, hh+1])
                cube([head_w*0.3, head_d*0.35, crest_h], center=true);

            // 侧面耳件 — 左右（向内偏移确保实体重叠）
            translate([-hw+2, 0, -3])
                ear_pod();
            translate([hw-2, 0, -3])
                ear_pod();
        }

        // 面罩凹槽（从正面挖入）
        translate([0, -hd, -3])
            cube([visor_w, 6, visor_h], center=true);
    }

    // 面罩底板（填回凹槽底部，略凹于头盔表面）
    translate([0, -hd+2, -3])
        cube([visor_w-2, 2, visor_h-2], center=true);

    // 左眼
    translate([-eye_sp/2, -hd+0.5, -2])
        rotate([90,0,0])
            cylinder(h=2.5, r=eye_r, $fn=quality/2);
    // 右眼
    translate([eye_sp/2, -hd+0.5, -2])
        rotate([90,0,0])
            cylinder(h=2.5, r=eye_r, $fn=quality/2);

    // 微笑
    translate([0, -hd+0.5, -6.5])
        rotate([90,0,0])
            cube([7, 1.5, 2], center=true);

    // 天线底座+杆+顶
    translate([0, 0, hh+crest_h]) {
        cylinder(h=2, r=ant_r+1.5, $fn=quality/2);
        translate([0,0,2])
            cylinder(h=ant_h, r=1.5, $fn=quality/3);
        translate([0,0,2+ant_h])
            cylinder(h=3, r=ant_r, $fn=quality/2);
    }
}

module ear_pod() {
    rotate([0,90,0]) {
        // 外圆筒
        cylinder(h=ear_d, r=ear_r, center=true, $fn=quality/2);
        // 内圆环装饰（与外筒齐平，不超出）
        difference() {
            cylinder(h=ear_d, r=ear_r*0.6, center=true, $fn=quality/2);
            cylinder(h=ear_d+1, r=ear_r*0.35, center=true, $fn=quality/2);
        }
    }
}

// ============================================================
// 躯干 Torso Module
// ============================================================
module torso() {
    tw = tor_w/2; th = tor_h; td = tor_d/2;

    // 主体：梯形方块（顶宽底窄）
    hull() {
        // 顶部
        translate([0, 0, th-2])
            cube([tor_w, tor_d, 4], center=true);
        // 底部（略窄）
        translate([0, 0, 1])
            cube([tor_w*0.8, tor_d*0.85, 2], center=true);
    }

    // 前胸甲板
    translate([0, -td-0.5, th*0.5])
        cube([chest_w, 2, chest_h], center=true);

    // 前胸甲板上的圆形装饰
    translate([0, -td-1.5, th*0.5])
        rotate([90,0,0])
            cylinder(h=1, r=4, $fn=quality/2);

    // 腰带
    translate([0, 0, 2])
        cube([tor_w+1, tor_d+1, 2.5], center=true);
}

// ============================================================
// 肩甲 Shoulder Pad Module
// ============================================================
module shoulder_pad() {
    // 方形肩甲，顶部略圆
    hull() {
        translate([0, 0, sh_h/2-2])
            cube([sh_w, sh_d, 2], center=true);
        translate([0, 0, -sh_h/2])
            cube([sh_w*0.9, sh_d*0.9, 2], center=true);
    }
    // 肩甲顶部凸条
    translate([0, 0, sh_h/2])
        cube([sh_w*0.6, sh_d*0.4, 2], center=true);
}

// ============================================================
// 手臂 Arm Module (side: 1=right, -1=left)
// ============================================================
module arm(side = 1) {
    rotate([0, side*arm_angle, 0]) {
        // 上臂
        translate([0, 0, -ua_len/2])
            cube([ua_w, ua_w, ua_len], center=true);

        // 肘关节球
        translate([0, 0, -ua_len])
            cube([ua_w+1, ua_w+1, 3], center=true);

        // 前臂装甲
        translate([0, 0, -ua_len - fa_len/2 - 2]) {
            // 前臂主体
            cube([fa_w, fa_w, fa_len], center=true);
            // 前臂装甲板
            translate([0, -fa_w/2-0.5, 0])
                cube([fa_w+2, 1.5, fa_len*0.8], center=true);
        }

        // 手/爪
        translate([0, 0, -ua_len - fa_len - 4]) {
            // 手掌
            cube([hand_w, hand_w*0.8, hand_w*0.7], center=true);
            // 手指槽
            for (dx=[-2.5, 2.5])
                translate([dx, -hand_w*0.4-0.5, -hand_w*0.15])
                    cube([1, 1, hand_w*0.5], center=true);
        }

        // 武器 (右臂才有)
        if (side == 1) {
            translate([0, -fa_w/2-2, -ua_len - fa_len/2 - 2])
                rotate([90,0,0]) {
                    // 枪管
                    cylinder(h=12, r=1.5, $fn=quality/3);
                    // 枪体
                    translate([0,0,-1])
                        cube([4, 3, 5], center=true);
                }
        }
    }
}

// ============================================================
// 腿 Leg Module
// ============================================================
module leg(side = 1) {
    // 髋关节
    cube([thigh_w*0.7, thigh_w*0.7, 3], center=true);

    // 大腿
    translate([0, 0, -thigh_len/2 - 1.5])
        cube([thigh_w, thigh_w*0.9, thigh_len], center=true);

    // 膝甲
    translate([0, -thigh_w/2, -thigh_len - 1]) {
        cube([knee_w, 3, 5], center=true);
    }

    // 膝关节
    translate([0, 0, -thigh_len - 2])
        cube([thigh_w+1, thigh_w+1, 3], center=true);

    // 小腿 — 向前倾斜收窄
    translate([0, 1, -thigh_len - calf_len/2 - 4])
        cube([calf_w, calf_w*0.9, calf_len], center=true);

    // 小腿装甲板（前面）
    translate([0, -calf_w/2, -thigh_len - calf_len/2 - 4])
        cube([calf_w+2, 2, calf_len*0.7], center=true);

    // 脚掌 — 分趾
    fz = -thigh_len - calf_len - 5;
    translate([0, 1, fz]) {
        // 脚跟
        translate([0, foot_d*0.15, 0])
            cube([foot_w*0.8, foot_d*0.5, foot_h], center=true);
        // 左脚趾
        translate([-foot_w*0.2, -foot_d*0.3, 0])
            cube([foot_w*0.35, foot_d*0.45, foot_h*0.8], center=true);
        // 右脚趾
        translate([foot_w*0.2, -foot_d*0.3, 0])
            cube([foot_w*0.35, foot_d*0.45, foot_h*0.8], center=true);
    }
}

// ============================================================
// 装配 Assembly
// ============================================================
scale([scale_factor, scale_factor, scale_factor]) {
    // 计算脚底位置以抬升到Z=0
    leg_total = thigh_len + calf_len + 5 + foot_h/2;
    lift = leg_total;

    translate([0, 0, lift]) {
        // 躯干
        torso();

        // 头盔（躯干顶部）
        translate([0, 0, tor_h + head_h/2 - 2])
            helmet();

        // 左肩甲
        translate([-(tor_w/2 + sh_w/2 - 2), 0, tor_h - 2])
            shoulder_pad();
        // 右肩甲
        translate([(tor_w/2 + sh_w/2 - 2), 0, tor_h - 2])
            shoulder_pad();

        // 左臂（肩甲下方）
        translate([-(tor_w/2 + 6), 0, tor_h - sh_h/2 - 2])
            arm(-1);
        // 右臂
        translate([(tor_w/2 + 6), 0, tor_h - sh_h/2 - 2])
            arm(1);

        // 左腿
        translate([-leg_sp/2, 0, 0])
            leg(-1);
        // 右腿
        translate([leg_sp/2, 0, 0])
            leg(1);
    }
}
