// ============================================================
// 咖啡杯 Coffee Mug — 参数化3D模型
// Generated by ModelForge (Cascade Agent)
// ============================================================

/* [杯身 / Body] */
body_height = 95;        // [60:1:150] 杯身高度 Body height (mm)
body_diameter = 82;      // [50:1:120] 杯身外径 Body outer diameter (mm)
wall_thickness = 3;      // [1.5:0.5:8] 壁厚 Wall thickness (mm)
bottom_thickness = 4;    // [2:0.5:10] 底部厚度 Bottom thickness (mm)
body_taper = 0.9;        // [0.75:0.01:1.0] 底部收缩比 Bottom taper ratio
lip_height = 2;          // [0:0.5:5] 杯口外翻高度 Lip height (mm)
lip_extra = 1.5;         // [0:0.5:4] 杯口外翻宽度 Lip extra width (mm)

/* [把手 / Handle] */
handle_width = 12;       // [8:1:20] 把手截面宽度 Handle cross-section width (mm)
handle_thickness = 8;    // [5:1:15] 把手截面厚度 Handle cross-section thickness (mm)
handle_span = 55;        // [30:1:80] 把手跨度(高度) Handle vertical span (mm)
handle_depth = 28;       // [15:1:45] 把手深度(伸出距离) Handle protrusion depth (mm)
handle_z_offset = 15;    // [5:1:40] 把手底部离杯底距离 Handle Z offset from bottom (mm)

/* [渲染 / Render] */
quality = 64;            // [16:8:128] 渲染精度 Render quality ($fn)

// ============================================================
// 杯身模块 Body Module
// ============================================================
module body() {
    outer_r_top = body_diameter / 2;
    outer_r_bot = outer_r_top * body_taper;
    inner_r_top = outer_r_top - wall_thickness;
    inner_r_bot = outer_r_bot - wall_thickness;

    difference() {
        union() {
            // 主杯身 - 锥形圆柱
            cylinder(
                h = body_height - lip_height,
                r1 = outer_r_bot,
                r2 = outer_r_top,
                $fn = quality
            );

            // 杯口外翻唇 Lip
            if (lip_height > 0) {
                translate([0, 0, body_height - lip_height])
                    cylinder(
                        h = lip_height,
                        r1 = outer_r_top,
                        r2 = outer_r_top + lip_extra,
                        $fn = quality
                    );
            }
        }

        // 内腔挖空
        translate([0, 0, bottom_thickness])
            cylinder(
                h = body_height - bottom_thickness + 1,
                r1 = inner_r_bot,
                r2 = inner_r_top + lip_extra,
                $fn = quality
            );
    }
}

// ============================================================
// 把手模块 Handle Module
// 4关键点hull连接，D形把手，计算快速
// ============================================================
module handle() {
    body_r = body_diameter / 2;
    bot_z = handle_z_offset;
    top_z = handle_z_offset + handle_span;
    mid_z = (bot_z + top_z) / 2;
    hw = handle_width;
    ht = handle_thickness;

    // 4个关键点: 顶部接杯身、中部外凸、底部接杯身
    // 上段
    hull() {
        // 顶部连接点（贴杯身）
        translate([0, -body_r + 1, top_z])
            cube([hw, ht, ht], center=true);
        // 中上外凸点
        translate([0, -body_r - handle_depth * 0.8, mid_z + handle_span * 0.15])
            cube([hw, ht, ht], center=true);
    }
    // 中段（最外凸）
    hull() {
        translate([0, -body_r - handle_depth * 0.8, mid_z + handle_span * 0.15])
            cube([hw, ht, ht], center=true);
        translate([0, -body_r - handle_depth, mid_z])
            cube([hw, ht, ht], center=true);
    }
    hull() {
        translate([0, -body_r - handle_depth, mid_z])
            cube([hw, ht, ht], center=true);
        translate([0, -body_r - handle_depth * 0.8, mid_z - handle_span * 0.15])
            cube([hw, ht, ht], center=true);
    }
    // 下段
    hull() {
        translate([0, -body_r - handle_depth * 0.8, mid_z - handle_span * 0.15])
            cube([hw, ht, ht], center=true);
        // 底部连接点（贴杯身）
        translate([0, -body_r + 1, bot_z])
            cube([hw, ht, ht], center=true);
    }
}

// ============================================================
// 装配 Assembly
// ============================================================
body();
handle();
