"""
VaM 插件代码生成器 — 程序化生成C#插件/Scripter脚本

从以下外部项目提取核心逻辑:
  - vam-plugin-template: MVRScript boilerplate, JSONStorable pattern
  - vam-scripter: In-VaM JavaScript scripting patterns
  - vam-devtools: Component inspection, UI creation patterns

架构:
  PluginGenerator    — C# VaM插件代码生成
  ScripterGenerator  — Scripter JavaScript脚本生成
  MetaGenerator      — meta.json生成 (VAR包元数据)
"""
import json
from pathlib import Path
from typing import Optional
from datetime import datetime, timezone

from .config import VAM_CONFIG


# ── C# 插件模板 ──

CS_PLUGIN_TEMPLATE = '''using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// {description}
/// Generated by VaM Agent on {timestamp}
/// </summary>
public class {class_name} : MVRScript
{{
{fields}

    public override void Init()
    {{
        try
        {{
{init_body}
        }}
        catch (Exception exc)
        {{
            SuperController.LogError($"{class_name}: Init failed: {{exc}}");
        }}
    }}
{methods}
}}
'''

CS_FIELD_BOOL = '    private JSONStorableBool _{name}JSON;'
CS_FIELD_FLOAT = '    private JSONStorableFloat _{name}JSON;'
CS_FIELD_STRING = '    private JSONStorableString _{name}JSON;'
CS_FIELD_ACTION = '    private JSONStorableAction _{name}JSON;'

CS_INIT_BOOL = '''            _{name}JSON = new JSONStorableBool("{display_name}", {default});
            RegisterBool(_{name}JSON);
            CreateToggle(_{name}JSON{side});'''

CS_INIT_FLOAT = '''            _{name}JSON = new JSONStorableFloat("{display_name}", {default}f, {min}f, {max}f);
            RegisterFloat(_{name}JSON);
            CreateSlider(_{name}JSON{side});'''

CS_INIT_STRING = '''            _{name}JSON = new JSONStorableString("{display_name}", "{default}");
            RegisterString(_{name}JSON);
            CreateTextField(_{name}JSON{side});'''

CS_INIT_ACTION = '''            _{name}JSON = new JSONStorableAction("{display_name}", () => {{
                {action_body}
            }});
            RegisterAction(_{name}JSON);
            CreateButton("{display_name}"{side});'''

CS_UPDATE_METHOD = '''
    public void Update()
    {{
{update_body}
    }}
'''

CS_ONDESTROY_METHOD = '''
    public void OnDestroy()
    {{
{destroy_body}
    }}
'''

CS_CALLBACK_TEMPLATE = '''            _{name}JSON.setCallbackFunction = ({type} val) => {{
                {callback_body}
            }};'''


# ── meta.json 模板 (from vamtb tpl) ──

META_TEMPLATE = {
    "licenseType": "CC BY-SA",
    "creatorName": "",
    "packageName": "",
    "standardReferenceVersionOption": "Latest",
    "scriptReferenceVersionOption": "Exact",
    "description": "",
    "credits": "",
    "instructions": "",
    "promotionalLink": "",
    "programVersion": "1.22.0.3",
    "contentList": [],
    "dependencies": {},
    "customOptions": {},
    "hadReferenceIssues": "false",
    "referenceIssues": [],
}


class PluginGenerator:
    """
    C# VaM插件代码生成器

    用法:
        gen = PluginGenerator("MyAwesomePlugin")
        gen.add_bool("enabled", "Enable Plugin", True)
        gen.add_float("speed", "Animation Speed", 1.0, 0.0, 10.0)
        gen.add_action("reset", "Reset All", "SuperController.LogMessage(\\"Reset!\\");")
        code = gen.generate()
        path = gen.deploy()
    """

    def __init__(self, class_name: str, description: str = ""):
        self.class_name = class_name
        self.description = description or f"VaM Plugin: {class_name}"
        self.storables: list[dict] = []
        self.has_update: bool = False
        self.update_body: str = ""
        self.has_destroy: bool = False
        self.destroy_body: str = ""
        self.extra_methods: list[str] = []
        self.extra_fields: list[str] = []
        self.using_statements: list[str] = []

    def add_bool(self, name: str, display_name: str = "",
                 default: bool = False, callback: str = "",
                 right_side: bool = False) -> "PluginGenerator":
        """添加布尔开关"""
        self.storables.append({
            "type": "bool", "name": name,
            "display_name": display_name or name,
            "default": "true" if default else "false",
            "callback": callback,
            "side": ", true" if right_side else "",
        })
        return self

    def add_float(self, name: str, display_name: str = "",
                  default: float = 0.0, min_val: float = 0.0,
                  max_val: float = 1.0, callback: str = "",
                  right_side: bool = False) -> "PluginGenerator":
        """添加浮点滑块"""
        self.storables.append({
            "type": "float", "name": name,
            "display_name": display_name or name,
            "default": default, "min": min_val, "max": max_val,
            "callback": callback,
            "side": ", true" if right_side else "",
        })
        return self

    def add_string(self, name: str, display_name: str = "",
                   default: str = "",
                   right_side: bool = False) -> "PluginGenerator":
        """添加文本字段"""
        self.storables.append({
            "type": "string", "name": name,
            "display_name": display_name or name,
            "default": default,
            "side": ", true" if right_side else "",
        })
        return self

    def add_action(self, name: str, display_name: str = "",
                   action_body: str = "",
                   right_side: bool = False) -> "PluginGenerator":
        """添加动作按钮"""
        self.storables.append({
            "type": "action", "name": name,
            "display_name": display_name or name,
            "action_body": action_body or f'SuperController.LogMessage("{name} triggered");',
            "side": ", true" if right_side else "",
        })
        return self

    def set_update(self, body: str) -> "PluginGenerator":
        """设置Update()方法体"""
        self.has_update = True
        self.update_body = body
        return self

    def set_on_destroy(self, body: str) -> "PluginGenerator":
        """设置OnDestroy()方法体"""
        self.has_destroy = True
        self.destroy_body = body
        return self

    def add_method(self, code: str) -> "PluginGenerator":
        """添加自定义方法"""
        self.extra_methods.append(code)
        return self

    def add_field(self, code: str) -> "PluginGenerator":
        """添加自定义字段"""
        self.extra_fields.append(code)
        return self

    def generate(self) -> str:
        """生成完整的C#插件代码"""
        fields_lines = []
        init_lines = []

        for s in self.storables:
            st = s["type"]
            if st == "bool":
                fields_lines.append(CS_FIELD_BOOL.format(**s))
                init_lines.append(CS_INIT_BOOL.format(**s))
                if s.get("callback"):
                    init_lines.append(CS_CALLBACK_TEMPLATE.format(
                        name=s["name"], type="bool",
                        callback_body=s["callback"],
                    ))
            elif st == "float":
                fields_lines.append(CS_FIELD_FLOAT.format(**s))
                init_lines.append(CS_INIT_FLOAT.format(**s))
                if s.get("callback"):
                    init_lines.append(CS_CALLBACK_TEMPLATE.format(
                        name=s["name"], type="float",
                        callback_body=s["callback"],
                    ))
            elif st == "string":
                fields_lines.append(CS_FIELD_STRING.format(**s))
                init_lines.append(CS_INIT_STRING.format(**s))
            elif st == "action":
                fields_lines.append(CS_FIELD_ACTION.format(**s))
                init_lines.append(CS_INIT_ACTION.format(**s))

        fields_lines.extend(self.extra_fields)

        methods = ""
        if self.has_update:
            methods += CS_UPDATE_METHOD.format(
                update_body=self.update_body
            )
        if self.has_destroy:
            methods += CS_ONDESTROY_METHOD.format(
                destroy_body=self.destroy_body
            )
        for m in self.extra_methods:
            methods += f"\n{m}\n"

        code = CS_PLUGIN_TEMPLATE.format(
            class_name=self.class_name,
            description=self.description,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M"),
            fields="\n".join(fields_lines),
            init_body="\n".join(init_lines) if init_lines
                else "            // No storables configured",
            methods=methods,
        )

        # 添加额外的using
        for us in self.using_statements:
            code = f"using {us};\n" + code

        return code

    def deploy(self, subdir: str = "Agent") -> str:
        """部署到VaM Custom/Scripts目录"""
        code = self.generate()
        target = VAM_CONFIG.SCRIPTS_DIR / subdir / f"{self.class_name}.cs"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(code, encoding="utf-8")
        return str(target)

    def save_local(self, filepath: Optional[str] = None) -> str:
        """保存到本地文件"""
        code = self.generate()
        if not filepath:
            filepath = str(
                VAM_CONFIG.AGENT_ROOT / "generated" / f"{self.class_name}.cs"
            )
        path = Path(filepath)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(code, encoding="utf-8")
        return str(path)


# ── Scripter 脚本生成 ──

SCRIPTER_JS_TEMPLATE = '''// {description}
// Generated by VaM Agent on {timestamp}

// Access atom storables
var atom = scene.GetAtomById("{atom_id}");

{script_body}
'''


class ScripterGenerator:
    """
    Scripter JavaScript脚本生成器

    为VaM内置的Scripter插件生成JavaScript脚本
    """

    def __init__(self, name: str, atom_id: str = "Person",
                 description: str = ""):
        self.name = name
        self.atom_id = atom_id
        self.description = description or f"Scripter script: {name}"
        self.script_lines: list[str] = []

    def add_line(self, line: str) -> "ScripterGenerator":
        """添加脚本行"""
        self.script_lines.append(line)
        return self

    def set_storable_value(self, storable_id: str, param: str,
                           value: str) -> "ScripterGenerator":
        """生成设置storable参数的代码"""
        self.script_lines.append(
            f'atom.GetStorableById("{storable_id}")'
            f'.SetStringParamValue("{param}", "{value}");'
        )
        return self

    def set_morph(self, morph_name: str,
                  value: float) -> "ScripterGenerator":
        """生成设置morph的代码"""
        self.script_lines.append(
            f'atom.GetStorableById("geometry")'
            f'.SetFloatParamValue("{morph_name}", {value}f);'
        )
        return self

    def trigger_action(self, storable_id: str,
                       action: str) -> "ScripterGenerator":
        """生成触发action的代码"""
        self.script_lines.append(
            f'atom.GetStorableById("{storable_id}")'
            f'.CallAction("{action}");'
        )
        return self

    def generate(self) -> str:
        """生成完整脚本"""
        return SCRIPTER_JS_TEMPLATE.format(
            description=self.description,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M"),
            atom_id=self.atom_id,
            script_body="\n".join(self.script_lines),
        )

    def deploy(self) -> str:
        """部署到Scripter目录"""
        code = self.generate()
        target = VAM_CONFIG.SCRIPTS_DIR / "Scripter" / f"{self.name}.js"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(code, encoding="utf-8")
        return str(target)


# ── meta.json 生成 (from vamtb template) ──

class MetaGenerator:
    """
    meta.json生成器 — VAR包元数据

    基于vamtb的f_gen_meta逻辑
    """

    def __init__(self, creator: str, package_name: str):
        self.creator = creator
        self.package_name = package_name
        self.description: str = ""
        self.credits: str = ""
        self.instructions: str = ""
        self.promotional_link: str = ""
        self.license_type: str = "CC BY-SA"
        self.content_list: list[str] = []
        self.dependencies: dict[str, dict] = {}

    def set_description(self, desc: str) -> "MetaGenerator":
        self.description = desc
        return self

    def set_license(self, license_type: str) -> "MetaGenerator":
        self.license_type = license_type
        return self

    def add_content(self, path: str) -> "MetaGenerator":
        """添加内容文件路径"""
        self.content_list.append(path)
        return self

    def add_dependency(self, var_name: str,
                       version: Optional[dict] = None) -> "MetaGenerator":
        """添加依赖"""
        self.dependencies[var_name] = version or {
            "licenseType": "CC BY",
            "dependencies": {},
        }
        return self

    def build(self) -> dict:
        """构建meta.json字典"""
        meta = META_TEMPLATE.copy()
        meta["creatorName"] = self.creator
        meta["packageName"] = self.package_name
        meta["description"] = self.description
        meta["credits"] = self.credits
        meta["instructions"] = self.instructions
        meta["promotionalLink"] = (
            self.promotional_link
            or datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
        )
        meta["licenseType"] = self.license_type
        meta["contentList"] = self.content_list
        meta["dependencies"] = self.dependencies
        return meta

    def save(self, filepath: str) -> str:
        """保存meta.json"""
        path = Path(filepath)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(self.build(), indent=3), encoding="utf-8"
        )
        return str(path)
