// ============================================================
// chibi_mech — Assembly
// Generated by ModelForge
// ============================================================

/* [Render] */
quality = 64;  // [16:8:128]
explode = 0;   // [0:5:100] Explode distance for assembly view

// Include sub-parts from parts/ directory
// use <parts/part_name.scad>

// Assembly
// part_a();
// translate([explode, 0, 0]) part_b();
